services:
  auth:
    image: localhost:5000/event-booking-platform-auth:latest
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  catalog:
    image: localhost:5000/event-booking-platform-catalog:latest
    env_file: .env
    ports:
      - "8002:8000"
    depends_on:
      - postgres

  booking:
    image: localhost:5000/event-booking-platform-booking:latest
    env_file: .env
    ports:
      - "8003:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - catalog
      - auth

  payment:
    image: localhost:5000/event-booking-platform-payment:latest
    env_file: .env
    ports:
      - "8004:8000"
    depends_on:
      - postgres
      - redis
      - auth
      - booking

  frontend:
    image: localhost:5000/event-booking-platform-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - catalog
      - booking
      - payment

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:


