apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: event-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      serviceAccountName: event-booking-sa
      containers:
      - name: frontend
        image: frontend-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: REACT_APP_API_URL
        - name: REACT_APP_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: REACT_APP_AUTH_URL
        - name: REACT_APP_CATALOG_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: REACT_APP_CATALOG_URL
        - name: REACT_APP_BOOKING_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: REACT_APP_BOOKING_URL
        - name: REACT_APP_PAYMENT_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: REACT_APP_PAYMENT_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: event-booking
spec:
  selector:
    app: frontend-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-service-hpa
  namespace: event-booking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
