apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: event-booking
data:
  rabbitmq.conf: |
    # RabbitMQ Configuration
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    management.tcp.ip = 0.0.0.0
    
    # Enable management plugin
    
    # Logging
    log.console = true
    log.console.level = info
    
    # Memory and disk limits
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.relative = 2.0
    
    # Cluster settings
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
    
    # Security
    default_user = admin
    default_pass = admin123
    default_vhost = /
    
    # Heartbeat
    heartbeat = 60
    
    # Connection limits
    num_acceptors.tcp = 10
    channel_max = 2047
    
    # Queue settings
    queue_master_locator = min-masters
    
    # Enable plugins
    management.tcp.port = 15672
    management.tcp.ip = 0.0.0.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
  namespace: event-booking
data:
  definitions.json: |
    {
      "rabbit_version": "3.13.0",
      "rabbitmq_version": "3.13.0",
      "product_name": "RabbitMQ",
      "product_version": "3.13.0",
      "users": [
        {
          "name": "admin",
          "password_hash": "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "admin",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [],
      "parameters": [],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": "rabbit@rabbitmq"
        }
      ],
      "policies": [],
      "queues": [
        {
          "name": "booking_queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "payment_queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "notification_queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [
        {
          "name": "booking_exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "payment_exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "notification_exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "booking_exchange",
          "vhost": "/",
          "destination": "booking_queue",
          "destination_type": "queue",
          "routing_key": "booking",
          "arguments": {}
        },
        {
          "source": "payment_exchange",
          "vhost": "/",
          "destination": "payment_queue",
          "destination_type": "queue",
          "routing_key": "payment",
          "arguments": {}
        },
        {
          "source": "notification_exchange",
          "vhost": "/",
          "destination": "notification_queue",
          "destination_type": "queue",
          "routing_key": "notification",
          "arguments": {}
        }
      ]
    }
