global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Event Booking Platform Services
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Infrastructure Services
  - job_name: 'postgres-primary'
    static_configs:
      - targets: ['postgres-primary:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres-replica'
    static_configs:
      - targets: ['postgres-replica:5433']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis-cluster'
    static_configs:
      - targets: ['redis-cluster:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Load Balancer
  - job_name: 'nginx-lb'
    static_configs:
      - targets: ['nginx-lb:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  # Node Exporter (if we add it later)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Custom metrics for business logic
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['auth:8000', 'catalog:8000', 'booking:8000', 'payment:8000']
    metrics_path: '/business-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'auth:8000/health'
        - 'catalog:8000/health'
        - 'booking:8000/health'
        - 'payment:8000/health'
        - 'frontend:3000'
        - 'nginx-lb:80/health'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

# Alerting rules (for future use)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules (for future use)
rule_files:
  # - "recording_rules.yml"
